<?php

namespace VoxSocioBundle\Repository;

/**
 * SocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocioRepository extends \Doctrine\ORM\EntityRepository
{
}
