homepage:
    path:     /
    defaults:  { _controller: VoxSocioBundle:socio:index }

vox_socio:
    resource: "@VoxSocioBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
